<?php
/**
 * @file first_module.module
 * TODO: Enter file description here.
 */


/**
 * Implements hook_help().
 */
function first_module_help($path, $arg) {
  switch ($path) {
    case 'admin/help#first_module':
      return t("This module is just for playing around");
  }
}

/**
 * Implements hook_menu().
 */
function first_module_menu() {
  $items['first_module/custom/%node'] = array(
    'title' => 'Custom page',
    'page callback' => 'first_module_custom',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Custom callback function
 */
function first_module_custom($node) {  
  // View of node
  $content = node_view($node); 

  return $content;
}

/**
 * Implements hook_form_alter().
 */
function first_module_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'article_node_form') {
    $form['field_message'] = array(
      '#type' => 'item',
      '#title' => t('New article'),
      '#markup' => t('You are about to create a new article'),
      '#weight' => -6,
    );
  }  
}

/**
 * Implements hook_user_login().
 */
function first_module_user_login(&$edit, $account) {
  drupal_set_message(t('Hi @name, thank you for logging in and welcome!', array('@name' => $account->name)));
}
